# Unit 3 - missing values
---

1. Find rows with missing values
2. Remove missing values using dropna()  
3. Fill missing values using fillna()
4. Fill missing values using interpolate()

In [1]:
import pandas as pd
import numpy as np

In [2]:
url = 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv'
vacc_df = pd.read_csv(url)

<a id='section1'></a>

`null` / `na` - no value

`NaN` - **N**ot **a** **N**umber - the value is missing. This value will be ignored in calculations such as `.mean()`


### 1. Find rows with missing values

In [3]:
vacc_df.isnull().sum()

location                                  0
iso_code                                  0
date                                      0
total_vaccinations                     6345
people_vaccinated                      7037
people_fully_vaccinated                9439
daily_vaccinations_raw                 7902
daily_vaccinations                      216
total_vaccinations_per_hundred         6345
people_vaccinated_per_hundred          7037
people_fully_vaccinated_per_hundred    9439
daily_vaccinations_per_million          216
dtype: int64

`isnull()` is a pandas function, so either use it on a dataframe or call it through pd

In [4]:
pd.isnull(vacc_df).sum()

location                                  0
iso_code                                  0
date                                      0
total_vaccinations                     6345
people_vaccinated                      7037
people_fully_vaccinated                9439
daily_vaccinations_raw                 7902
daily_vaccinations                      216
total_vaccinations_per_hundred         6345
people_vaccinated_per_hundred          7037
people_fully_vaccinated_per_hundred    9439
daily_vaccinations_per_million          216
dtype: int64

In [5]:
vacc_df['daily_vaccinations'].notnull().sum()

16883

In [6]:
vacc_df['daily_vaccinations'].isnull().sum()

216

`isnan` is a numpy function

In [7]:
np.isnan(vacc_df['daily_vaccinations']).sum()

216

### 2. Remove missing values using dropna()

Zimbabwe contains missing values

In [8]:
zimbabwe = vacc_df.loc[vacc_df.location == 'Zimbabwe']
zimbabwe.head(10)

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
17018,Zimbabwe,ZWE,2021-02-18,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN
17019,Zimbabwe,ZWE,2021-02-19,NaN,NaN,NaN,NaN,328.0,NaN,NaN,NaN,22.0
17020,Zimbabwe,ZWE,2021-02-20,NaN,NaN,NaN,NaN,328.0,NaN,NaN,NaN,22.0
17021,Zimbabwe,ZWE,2021-02-21,NaN,NaN,NaN,NaN,328.0,NaN,NaN,NaN,22.0
17022,Zimbabwe,ZWE,2021-02-22,1314.0,1314.0,NaN,NaN,328.0,0.01,0.01,NaN,22.0
17023,Zimbabwe,ZWE,2021-02-23,4041.0,4041.0,NaN,2727.0,808.0,0.03,0.03,NaN,54.0
17024,Zimbabwe,ZWE,2021-02-24,7872.0,7872.0,NaN,3831.0,1312.0,0.05,0.05,NaN,88.0
17025,Zimbabwe,ZWE,2021-02-25,11007.0,11007.0,NaN,3135.0,1572.0,0.07,0.07,NaN,106.0
17026,Zimbabwe,ZWE,2021-02-26,12579.0,12579.0,NaN,1572.0,1750.0,0.08,0.08,NaN,118.0
17027,Zimbabwe,ZWE,2021-02-27,15705.0,15705.0,NaN,3126.0,2150.0,0.11,0.11,NaN,145.0

In [9]:
zimbabwe['total_vaccinations'].isnull().sum()

3

In [10]:
zimbabwe['total_vaccinations'].notnull().sum()

78

We can see the difference between the number of values per row

In [11]:
zimbabwe.count()

location                               81
iso_code                               81
date                                   81
total_vaccinations                     78
people_vaccinated                      78
people_fully_vaccinated                49
daily_vaccinations_raw                 76
daily_vaccinations                     80
total_vaccinations_per_hundred         78
people_vaccinated_per_hundred          78
people_fully_vaccinated_per_hundred    49
daily_vaccinations_per_million         80
dtype: int64

Remove all values for a specific column

In [12]:
zimbabwe.dropna(subset = ['total_vaccinations']).count()

location                               78
iso_code                               78
date                                   78
total_vaccinations                     78
people_vaccinated                      78
people_fully_vaccinated                49
daily_vaccinations_raw                 76
daily_vaccinations                     77
total_vaccinations_per_hundred         78
people_vaccinated_per_hundred          78
people_fully_vaccinated_per_hundred    49
daily_vaccinations_per_million         77
dtype: int64

For more columns

In [13]:
zimbabwe.dropna(subset = ['total_vaccinations', 'daily_vaccinations_per_million']).head().count()

location                               5
iso_code                               5
date                                   5
total_vaccinations                     5
people_vaccinated                      5
people_fully_vaccinated                0
daily_vaccinations_raw                 4
daily_vaccinations                     5
total_vaccinations_per_hundred         5
people_vaccinated_per_hundred          5
people_fully_vaccinated_per_hundred    0
daily_vaccinations_per_million         5
dtype: int64

For all columns

In [14]:
zimbabwe.dropna()

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
17050,Zimbabwe,ZWE,2021-03-22,43574.0,43294.0,280.0,845.0,845.0,0.29,0.29,0.00,57.0
17051,Zimbabwe,ZWE,2021-03-23,45197.0,44135.0,1062.0,1623.0,807.0,0.30,0.30,0.01,54.0
17052,Zimbabwe,ZWE,2021-03-24,51893.0,49404.0,2489.0,6696.0,1755.0,0.35,0.33,0.02,118.0
17053,Zimbabwe,ZWE,2021-03-25,58987.0,54892.0,4095.0,7094.0,2712.0,0.40,0.37,0.03,182.0
17054,Zimbabwe,ZWE,2021-03-26,67662.0,61093.0,6569.0,8675.0,3711.0,0.46,0.41,0.04,250.0
17055,Zimbabwe,ZWE,2021-03-27,73431.0,65466.0,7965.0,5769.0,4460.0,0.49,0.44,0.05,300.0
17056,Zimbabwe,ZWE,2021-03-28,79139.0,68511.0,10628.0,5708.0,5201.0,0.53,0.46,0.07,350.0
17057,Zimbabwe,ZWE,2021-03-29,81610.0,69751.0,11859.0,2471.0,5434.0,0.55,0.47,0.08,366.0
17058,Zimbabwe,ZWE,2021-03-30,85866.0,72944.0,12922.0,4256.0,5810.0,0.58,0.49,0.09,391.0
17059,Zimbabwe,ZWE,2021-03-31,91880.0,76995.0,14885.0,6014.0,5712.0,0.62,0.52,0.10,384.0
17060,Zimbabwe,ZWE,2021-04-01,105307.0,87791.0,17516.0,13427.0,6617.0,0.71,0.59,0.12,445.0
17061,Zimbabwe,ZWE,2021-04-02,124753.0,103815.0,20938.0,19446.0,8156.0,0.84,0.70,0.14,549.0
17062,Zimbabwe,ZWE,2021-04-03,132915.0,111588.0,21327.0,8162.0,8498.0,0.89,0.75,0.14,572.0
17063,Zimbabwe,ZWE,2021-04-04,138900.0,117297.0,21603.0,5985.0,8537.0,0.93,0.79,0.15,574.0
17064,Zimbabwe,ZWE,2021-04-05,145510.0,123454.0,22056.0,6610.0,9129.0,0.98,0.83,0.15,614.0
17065,Zimbabwe,ZWE,2021-04-06,162633.0,139133.0,23500.0,17123.0,10967.0,1.09,0.94,0.16,738.0
17066,Zimbabwe,ZWE,2021-04-07,179417.0,153238.0,26179.0,16784.0,12505.0,1.21,1.03,0.18,841.0
17067,Zimbabwe,ZWE,2021-04-08,193677.0,166543.0,27134.0,14260.0,12624.0,1.30,1.12,0.18,849.0
17068,Zimbabwe,ZWE,2021-04-09,206205.0,178237.0,27968.0,12528.0,11636.0,1.39,1.20,0.19,783.0
17069,Zimbabwe,ZWE,2021-04-10,222733.0,193936.0,28797.0,16528.0,12831.0,1.50,1.30,0.19,863.0
17070,Zimbabwe,ZWE,2021-04-11,223492.0,194594.0,28898.0,759.0,12085.0,1.50,1.31,0.19,813.0
17071,Zimbabwe,ZWE,2021-04-12,234579.0,205275.0,29304.0,11087.0,12724.0,1.58,1.38,0.20,856.0
17072,Zimbabwe,ZWE,2021-04-13,248355.0,218516.0,29839.0,13776.0,12246.0,1.67,1.47,0.20,824.0
17073,Zimbabwe,ZWE,2021-04-14,262128.0,231632.0,30496.0,13773.0,11816.0,1.76,1.56,0.21,795.0
17074,Zimbabwe,ZWE,2021-04-15,285881.0,252932.0,32949.0,23753.0,13172.0,1.92,1.70,0.22,886.0
17075,Zimbabwe,ZWE,2021-04-16,304701.0,269732.0,34969.0,18820.0,14071.0,2.05,1.81,0.24,947.0
17076,Zimbabwe,ZWE,2021-04-17,311901.0,276095.0,35806.0,7200.0,12738.0,2.10,1.86,0.24,857.0
17077,Zimbabwe,ZWE,2021-04-18,314446.0,278583.0,35863.0,2545.0,12993.0,2.12,1.87,0.24,874.0
17078,Zimbabwe,ZWE,2021-04-19,316991.0,280568.0,36423.0,2545.0,11773.0,2.13,1.89,0.25,792.0
17079,Zimbabwe,ZWE,2021-04-20,325007.0,288229.0,36778.0,8016.0,10950.0,2.19,1.94,0.25,737.0
17080,Zimbabwe,ZWE,2021-04-21,332996.0,295631.0,37365.0,7989.0,10124.0,2.24,1.99,0.25,681.0
17081,Zimbabwe,ZWE,2021-04-22,351799.0,308071.0,43728.0,18803.0,9417.0,2.37,2.07,0.29,634.0
17082,Zimbabwe,ZWE,2021-04-23,365985.0,319732.0,46253.0,14186.0,8755.0,2.46,2.15,0.31,589.0
17083,Zimbabwe,ZWE,2021-04-24,372099.0,324488.0,47611.0,6114.0,8600.0,2.50,2.18,0.32,579.0
17084,Zimbabwe,ZWE,2021-04-25,390018.0,336600.0,53418.0,17919.0,10796.0,2.62,2.26,0.36,726.0
17085,Zimbabwe,ZWE,2021-04-26,411610.0,353834.0,57776.0,21592.0,13517.0,2.77,2.38,0.39,909.0
17086,Zimbabwe,ZWE,2021-04-27,433939.0,370676.0,63263.0,22329.0,15562.0,2.92,2.49,0.43,1047.0
17087,Zimbabwe,ZWE,2021-04-28,458013.0,388021.0,69992.0,24074.0,17860.0,3.08,2.61,0.47,1202.0
17088,Zimbabwe,ZWE,2021-04-29,477597.0,400771.0,76826.0,19584.0,17971.0,3.21,2.70,0.52,1209.0
17089,Zimbabwe,ZWE,2021-04-30,500342.0,414735.0,85607.0,22745.0,19194.0,3.37,2.79,0.58,1291.0
17090,Zimbabwe,ZWE,2021-05-01,520299.0,428135.0,92164.0,19957.0,21171.0,3.50,2.88,0.62,1424.0
17091,Zimbabwe,ZWE,2021-05-02,524199.0,430068.0,94131.0,3900.0,19169.0,3.53,2.89,0.63,1290.0
17092,Zimbabwe,ZWE,2021-05-03,537516.0,437751.0,99765.0,13317.0,17987.0,3.62,2.95,0.67,1210.0
17093,Zimbabwe,ZWE,2021-05-04,559777.0,452191.0,107586.0,22261.0,17977.0,3.77,3.04,0.72,1210.0
17094,Zimbabwe,ZWE,2021-05-05,576233.0,461023.0,115210.0,16456.0,16889.0,3.88,3.10,0.78,1136.0
17095,Zimbabwe,ZWE,2021-05-06,607355.0,478174.0,129181.0,31122.0,18537.0,4.09,3.22,0.87,1247.0
17096,Zimbabwe,ZWE,2021-05-07,640762.0,500422.0,140340.0,33407.0,20060.0,4.31,3.37,0.94,1350.0
17097,Zimbabwe,ZWE,2021-05-08,657838.0,509274.0,148564.0,17076.0,19648.0,4.43,3.43,1.00,1322.0
17098,Zimbabwe,ZWE,2021-05-09,684243.0,526066.0,158177.0,26405.0,22863.0,4.60,3.54,1.06,1538.0

Note: `dropna()`, like most other functions in the pandas API returns a new DataFrame 
(a copy of the original with changes) as the result, so you should assign it back if you want to see changes:

In [15]:
zimbabwe.count()

location                               81
iso_code                               81
date                                   81
total_vaccinations                     78
people_vaccinated                      78
people_fully_vaccinated                49
daily_vaccinations_raw                 76
daily_vaccinations                     80
total_vaccinations_per_hundred         78
people_vaccinated_per_hundred          78
people_fully_vaccinated_per_hundred    49
daily_vaccinations_per_million         80
dtype: int64

assign it back:

In [16]:
zimbabwe2 = zimbabwe.dropna()
zimbabwe2

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
17050,Zimbabwe,ZWE,2021-03-22,43574.0,43294.0,280.0,845.0,845.0,0.29,0.29,0.00,57.0
17051,Zimbabwe,ZWE,2021-03-23,45197.0,44135.0,1062.0,1623.0,807.0,0.30,0.30,0.01,54.0
17052,Zimbabwe,ZWE,2021-03-24,51893.0,49404.0,2489.0,6696.0,1755.0,0.35,0.33,0.02,118.0
17053,Zimbabwe,ZWE,2021-03-25,58987.0,54892.0,4095.0,7094.0,2712.0,0.40,0.37,0.03,182.0
17054,Zimbabwe,ZWE,2021-03-26,67662.0,61093.0,6569.0,8675.0,3711.0,0.46,0.41,0.04,250.0
17055,Zimbabwe,ZWE,2021-03-27,73431.0,65466.0,7965.0,5769.0,4460.0,0.49,0.44,0.05,300.0
17056,Zimbabwe,ZWE,2021-03-28,79139.0,68511.0,10628.0,5708.0,5201.0,0.53,0.46,0.07,350.0
17057,Zimbabwe,ZWE,2021-03-29,81610.0,69751.0,11859.0,2471.0,5434.0,0.55,0.47,0.08,366.0
17058,Zimbabwe,ZWE,2021-03-30,85866.0,72944.0,12922.0,4256.0,5810.0,0.58,0.49,0.09,391.0
17059,Zimbabwe,ZWE,2021-03-31,91880.0,76995.0,14885.0,6014.0,5712.0,0.62,0.52,0.10,384.0
17060,Zimbabwe,ZWE,2021-04-01,105307.0,87791.0,17516.0,13427.0,6617.0,0.71,0.59,0.12,445.0
17061,Zimbabwe,ZWE,2021-04-02,124753.0,103815.0,20938.0,19446.0,8156.0,0.84,0.70,0.14,549.0
17062,Zimbabwe,ZWE,2021-04-03,132915.0,111588.0,21327.0,8162.0,8498.0,0.89,0.75,0.14,572.0
17063,Zimbabwe,ZWE,2021-04-04,138900.0,117297.0,21603.0,5985.0,8537.0,0.93,0.79,0.15,574.0
17064,Zimbabwe,ZWE,2021-04-05,145510.0,123454.0,22056.0,6610.0,9129.0,0.98,0.83,0.15,614.0
17065,Zimbabwe,ZWE,2021-04-06,162633.0,139133.0,23500.0,17123.0,10967.0,1.09,0.94,0.16,738.0
17066,Zimbabwe,ZWE,2021-04-07,179417.0,153238.0,26179.0,16784.0,12505.0,1.21,1.03,0.18,841.0
17067,Zimbabwe,ZWE,2021-04-08,193677.0,166543.0,27134.0,14260.0,12624.0,1.30,1.12,0.18,849.0
17068,Zimbabwe,ZWE,2021-04-09,206205.0,178237.0,27968.0,12528.0,11636.0,1.39,1.20,0.19,783.0
17069,Zimbabwe,ZWE,2021-04-10,222733.0,193936.0,28797.0,16528.0,12831.0,1.50,1.30,0.19,863.0
17070,Zimbabwe,ZWE,2021-04-11,223492.0,194594.0,28898.0,759.0,12085.0,1.50,1.31,0.19,813.0
17071,Zimbabwe,ZWE,2021-04-12,234579.0,205275.0,29304.0,11087.0,12724.0,1.58,1.38,0.20,856.0
17072,Zimbabwe,ZWE,2021-04-13,248355.0,218516.0,29839.0,13776.0,12246.0,1.67,1.47,0.20,824.0
17073,Zimbabwe,ZWE,2021-04-14,262128.0,231632.0,30496.0,13773.0,11816.0,1.76,1.56,0.21,795.0
17074,Zimbabwe,ZWE,2021-04-15,285881.0,252932.0,32949.0,23753.0,13172.0,1.92,1.70,0.22,886.0
17075,Zimbabwe,ZWE,2021-04-16,304701.0,269732.0,34969.0,18820.0,14071.0,2.05,1.81,0.24,947.0
17076,Zimbabwe,ZWE,2021-04-17,311901.0,276095.0,35806.0,7200.0,12738.0,2.10,1.86,0.24,857.0
17077,Zimbabwe,ZWE,2021-04-18,314446.0,278583.0,35863.0,2545.0,12993.0,2.12,1.87,0.24,874.0
17078,Zimbabwe,ZWE,2021-04-19,316991.0,280568.0,36423.0,2545.0,11773.0,2.13,1.89,0.25,792.0
17079,Zimbabwe,ZWE,2021-04-20,325007.0,288229.0,36778.0,8016.0,10950.0,2.19,1.94,0.25,737.0
17080,Zimbabwe,ZWE,2021-04-21,332996.0,295631.0,37365.0,7989.0,10124.0,2.24,1.99,0.25,681.0
17081,Zimbabwe,ZWE,2021-04-22,351799.0,308071.0,43728.0,18803.0,9417.0,2.37,2.07,0.29,634.0
17082,Zimbabwe,ZWE,2021-04-23,365985.0,319732.0,46253.0,14186.0,8755.0,2.46,2.15,0.31,589.0
17083,Zimbabwe,ZWE,2021-04-24,372099.0,324488.0,47611.0,6114.0,8600.0,2.50,2.18,0.32,579.0
17084,Zimbabwe,ZWE,2021-04-25,390018.0,336600.0,53418.0,17919.0,10796.0,2.62,2.26,0.36,726.0
17085,Zimbabwe,ZWE,2021-04-26,411610.0,353834.0,57776.0,21592.0,13517.0,2.77,2.38,0.39,909.0
17086,Zimbabwe,ZWE,2021-04-27,433939.0,370676.0,63263.0,22329.0,15562.0,2.92,2.49,0.43,1047.0
17087,Zimbabwe,ZWE,2021-04-28,458013.0,388021.0,69992.0,24074.0,17860.0,3.08,2.61,0.47,1202.0
17088,Zimbabwe,ZWE,2021-04-29,477597.0,400771.0,76826.0,19584.0,17971.0,3.21,2.70,0.52,1209.0
17089,Zimbabwe,ZWE,2021-04-30,500342.0,414735.0,85607.0,22745.0,19194.0,3.37,2.79,0.58,1291.0
17090,Zimbabwe,ZWE,2021-05-01,520299.0,428135.0,92164.0,19957.0,21171.0,3.50,2.88,0.62,1424.0
17091,Zimbabwe,ZWE,2021-05-02,524199.0,430068.0,94131.0,3900.0,19169.0,3.53,2.89,0.63,1290.0
17092,Zimbabwe,ZWE,2021-05-03,537516.0,437751.0,99765.0,13317.0,17987.0,3.62,2.95,0.67,1210.0
17093,Zimbabwe,ZWE,2021-05-04,559777.0,452191.0,107586.0,22261.0,17977.0,3.77,3.04,0.72,1210.0
17094,Zimbabwe,ZWE,2021-05-05,576233.0,461023.0,115210.0,16456.0,16889.0,3.88,3.10,0.78,1136.0
17095,Zimbabwe,ZWE,2021-05-06,607355.0,478174.0,129181.0,31122.0,18537.0,4.09,3.22,0.87,1247.0
17096,Zimbabwe,ZWE,2021-05-07,640762.0,500422.0,140340.0,33407.0,20060.0,4.31,3.37,0.94,1350.0
17097,Zimbabwe,ZWE,2021-05-08,657838.0,509274.0,148564.0,17076.0,19648.0,4.43,3.43,1.00,1322.0
17098,Zimbabwe,ZWE,2021-05-09,684243.0,526066.0,158177.0,26405.0,22863.0,4.60,3.54,1.06,1538.0

---
>A summary of the functions so far:
>
>* `.isnull()` - display rows that contain missing values
>* `.notnull()` - display rows that don't contain missing values
>* `.dropna()` - Remove rows with missing values according to parameters:
    * `.dropna()` (default) - drops rows if at least one column has NaN
    * `.dropna(how='all')` - drops rows only if all of its columns have NaNs
    * `.dropna(thresh = k)` - k how many non-null values you want to keep (k=3 means the row should contain at least 3 non-null values)
    * `.dropna(axis=1)` - drop columns instead of rows
> 

See documnetation [here.](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html)

---

### 3. Fill missing values using fillna()

Use `.fillna()` to fill missing dataframe values with:
* Whatever value you choose
* Mean, median, mode

Replace all NaNs with 0s

In [17]:
vacc_df.fillna(0, inplace = False )
vacc_df

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...
17094,Zimbabwe,ZWE,2021-05-05,576233.0,461023.0,115210.0,16456.0,16889.0,3.88,3.10,0.78,1136.0
17095,Zimbabwe,ZWE,2021-05-06,607355.0,478174.0,129181.0,31122.0,18537.0,4.09,3.22,0.87,1247.0
17096,Zimbabwe,ZWE,2021-05-07,640762.0,500422.0,140340.0,33407.0,20060.0,4.31,3.37,0.94,1350.0
17097,Zimbabwe,ZWE,2021-05-08,657838.0,509274.0,148564.0,17076.0,19648.0,4.43,3.43,1.00,1322.0
17098,Zimbabwe,ZWE,2021-05-09,684243.0,526066.0,158177.0,26405.0,22863.0,4.60,3.54,1.06,1538.0

>`inplace = False` is the default. This doesn't change the vacc_df dataframe. 
>
>To change it you need:
>
>`vacc_df.fillna(0 , inplace = True)`
>
>or to assign:
>
>`vacc_df = vacc_df.fillna(0)`
>
>But we won't do that! This is where some **business understanding** comes in: it's not a good idea to fill a column like `total_vaccinations` with 0s. 
>
>See what happens:

In [18]:
vacc_df.fillna(0).head(15)

,location,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
0,Afghanistan,AFG,2021-02-22,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0
1,Afghanistan,AFG,2021-02-23,0.0,0.0,0.0,0.0,1367.0,0.00,0.00,0.0,35.0
2,Afghanistan,AFG,2021-02-24,0.0,0.0,0.0,0.0,1367.0,0.00,0.00,0.0,35.0
3,Afghanistan,AFG,2021-02-25,0.0,0.0,0.0,0.0,1367.0,0.00,0.00,0.0,35.0
4,Afghanistan,AFG,2021-02-26,0.0,0.0,0.0,0.0,1367.0,0.00,0.00,0.0,35.0
5,Afghanistan,AFG,2021-02-27,0.0,0.0,0.0,0.0,1367.0,0.00,0.00,0.0,35.0
6,Afghanistan,AFG,2021-02-28,8200.0,8200.0,0.0,0.0,1367.0,0.02,0.02,0.0,35.0
7,Afghanistan,AFG,2021-03-01,0.0,0.0,0.0,0.0,1580.0,0.00,0.00,0.0,41.0
8,Afghanistan,AFG,2021-03-02,0.0,0.0,0.0,0.0,1794.0,0.00,0.00,0.0,46.0
9,Afghanistan,AFG,2021-03-03,0.0,0.0,0.0,0.0,2008.0,0.00,0.00,0.0,52.0
10,Afghanistan,AFG,2021-03-04,0.0,0.0,0.0,0.0,2221.0,0.00,0.00,0.0,57.0
11,Afghanistan,AFG,2021-03-05,0.0,0.0,0.0,0.0,2435.0,0.00,0.00,0.0,63.0
12,Afghanistan,AFG,2021-03-06,0.0,0.0,0.0,0.0,2649.0,0.00,0.00,0.0,68.0
13,Afghanistan,AFG,2021-03-07,0.0,0.0,0.0,0.0,2862.0,0.00,0.00,0.0,74.0
14,Afghanistan,AFG,2021-03-08,0.0,0.0,0.0,0.0,2862.0,0.00,0.00,0.0,74.0

So we'll use 0's only for the daily_vaccinations columns, and perhaps for some other columns (which?)

In [19]:
vacc_df['daily_vaccinations'].fillna(0 , inplace = True)

checkout some of the data to see that it works

In [20]:
vacc_df.iloc[0:3,[0,2,7]]

      location        date  daily_vaccinations
0  Afghanistan  2021-02-22                 0.0
1  Afghanistan  2021-02-23              1367.0
2  Afghanistan  2021-02-24              1367.0

What about `total_vaccinations`?

In [21]:
vacc_df.iloc[52:62,[0,2,3]]

       location        date  total_vaccinations
52  Afghanistan  2021-04-15                 NaN
53  Afghanistan  2021-04-16                 NaN
54  Afghanistan  2021-04-17                 NaN
55  Afghanistan  2021-04-18                 NaN
56  Afghanistan  2021-04-19                 NaN
57  Afghanistan  2021-04-20                 NaN
58  Afghanistan  2021-04-21                 NaN
59  Afghanistan  2021-04-22            240000.0
60       Africa  2021-01-09                 0.0
61       Africa  2021-01-10                 NaN

For the `total_vaccinations` we'll use `ffill` which fills the missing values with first non-missing value that occurs before it.

Yes, `bfill` exists as well. If does what you think it does :-)

In [22]:
vacc_df['total_vaccinations'].fillna(method='ffill')[52:62]
#vacc_df['total_vaccinations'][52:62]

52    120000.0
53    120000.0
54    120000.0
55    120000.0
56    120000.0
57    120000.0
58    120000.0
59    240000.0
60         0.0
61         0.0
Name: total_vaccinations, dtype: float64

The first value for some country might be NaN 

Business understanding: this isn't good enought! We need to aggregate by country!!

In [23]:
vacc_df.iloc[57:62,[0,2,3]]

       location        date  total_vaccinations
57  Afghanistan  2021-04-20                 NaN
58  Afghanistan  2021-04-21                 NaN
59  Afghanistan  2021-04-22            240000.0
60       Africa  2021-01-09                 0.0
61       Africa  2021-01-10                 NaN

Use `groupby()` and `apply`

(This is more advanced and we will learn it later)

In [24]:
vacc_df['newTotal'] = vacc_df.groupby('location')['total_vaccinations'].apply(lambda x: x.fillna(method='ffill'))
vacc_df.iloc[52:62,[0,2,3,12]]

       location        date  total_vaccinations  newTotal
52  Afghanistan  2021-04-15                 NaN  120000.0
53  Afghanistan  2021-04-16                 NaN  120000.0
54  Afghanistan  2021-04-17                 NaN  120000.0
55  Afghanistan  2021-04-18                 NaN  120000.0
56  Afghanistan  2021-04-19                 NaN  120000.0
57  Afghanistan  2021-04-20                 NaN  120000.0
58  Afghanistan  2021-04-21                 NaN  120000.0
59  Afghanistan  2021-04-22            240000.0  240000.0
60       Africa  2021-01-09                 0.0       0.0
61       Africa  2021-01-10                 NaN       0.0

Other options - using central measures:

(this is without grouping by country)

In [ ]:
# Using median
vacc_df['daily_vaccinations'].fillna(vacc_df['daily_vaccinations'].median(), inplace=True)
  
# Using mean
#vacc_df['daily_vaccinations'].fillna(vacc_df['daily_vaccinations'].mean(), inplace=True)
  
# Using mode
#vacc_df['daily_vaccinations'].fillna(vacc_df['daily_vaccinations'].mode(), inplace=True)

### 4. Fill missing values using interpolate()

In [ ]:
vacc_df['total_vaccinations'].interpolate(method ='linear',  inplace = True) 
vacc_df.iloc[52:62,[0,2,3]]

---
>A summary of the functions so far:
>
>* `.fillna()` - fill missing values according to parameters:
    * `.fillna('k')`  - with value k, create a new dataframe
    * `.fillna('k', inplace = True)` - with value k, into the existing dataframe
    * `.fillna(method='ffill')` - fill with first non-missing value that occurs before it 
    * `.fillna(method='bfill')` - fill with first non-missing value that occurs after it  
> * `interpolate` - fill using some interpolation technique
>
>See documnetation:
>
>* [Missing data handling documentation](https://pandas-docs.github.io/pandas-docs-travis/reference/frame.html#missing-data-handling)
---